server:
  port: 8080

jwt:
  secret: "banco-parte3-jwt-secret-compartido-entre-customer-service-y-api-gateway-cambiar-en-produccion"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
